<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import { documentosApi, linksApi } from '../api/resources'; import { errorMessage } from '../api/client'; import type { Documento, Link } from '../types'
const route = useRoute(); const id = Number(route.params.id); const doc = ref<Documento | null>(null); const links = ref<Link[]>([]); const error = ref(''); const copied = ref('')
const format = (v: string | null) => v ? new Date(v).toLocaleString('pt-BR') : 'Sem expiração'
async function load() { try { [doc.value, links.value] = await Promise.all([documentosApi.buscar(id).then(x => x.data), documentosApi.links(id).then(x => x.data)]) } catch (e) { error.value = errorMessage(e) } }
async function copy(link: Link) { await navigator.clipboard.writeText(link.urlCompleta); copied.value = String(link.id); setTimeout(() => copied.value = '', 1500) }
async function toggle(link: Link) { try { await (link.revogado ? linksApi.reativar(link.id) : linksApi.revogar(link.id)); await load() } catch (e) { error.value = errorMessage(e) } }
onMounted(load)
</script>
<template><section class="page"><header class="page-header"><div><p class="eyebrow">Documento</p><h1>{{ doc?.nomeOriginal || 'Carregando...' }}</h1><p class="muted">{{ doc?.municipio }} · {{ doc?.periodoFormatado }} · {{ doc?.tipoImposto.sigla }}</p></div><RouterLink class="primary button" :to="`/documentos/${id}/links/novo`">Gerar link</RouterLink></header><p v-if="error" class="alert error">{{ error }}</p><div class="card details" v-if="doc"><span>Enviado em <strong>{{ format(doc.dataUpload) }}</strong></span><span>{{ doc.tamanhoBytes.toLocaleString('pt-BR') }} bytes</span><span>{{ doc.quantidadeLinks }} links</span></div><h2>Links de compartilhamento</h2><div class="card table-wrap"><table><thead><tr><th>Status</th><th>Proteção</th><th>Expiração</th><th>URL</th><th></th></tr></thead><tbody><tr v-for="link in links" :key="link.id"><td><span class="badge" :class="link.ativo ? 'success' : 'neutral'">{{ link.ativo ? 'Ativo' : link.revogado ? 'Revogado' : 'Expirado' }}</span></td><td>{{ link.exigeSenha ? 'Com senha' : 'Sem senha' }}</td><td>{{ format(link.expiresAt) }}</td><td class="url">{{ link.urlCompleta }}</td><td class="actions"><button @click="copy(link)">{{ copied === String(link.id) ? 'Copiado!' : 'Copiar' }}</button><RouterLink :to="`/links/${link.id}/editar`">Editar</RouterLink><button @click="toggle(link)">{{ link.revogado ? 'Reativar' : 'Revogar' }}</button></td></tr><tr v-if="!links.length"><td colspan="5" class="muted">Nenhum link criado.</td></tr></tbody></table></div></section></template>